server:
  port: 8080

eureka:
  client:
    register-with-eureka: true   # Ensures the gateway registers itself with Eureka
    fetch-registry: true         # Allows gateway to discover other services
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    preferIpAddress: true

spring:
  security:
    exclude-paths:
      - /api/user/register
      - /api/auth/sign-in
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: stone-read
          uri: lb://stone-read
          predicates:
            - Path=/stone-read/**
          filters:
            - StripPrefix=1
        - id: stone-write
          uri: lb://stone-write
          predicates:
            - Path=/stone-write/**
          filters:
            - StripPrefix=1
kamyczki:
  auth-service: localhost:8081