server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://registry:8761/eureka/

spring:
  application:
    name: stone-write

  data:
    mongodb:
      uri: mongodb+srv://kamyczkidev:FLVSl94OVh8aJPXH@kamyczkidev.yb6yp.mongodb.net/stone_events

  kafka:
    bootstrap-servers: localhost:9200
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 1
      buffer-memory: 33554432